# Generated by Django 3.1.2 on 2021-04-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paystack_ref_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
